- name: Common settings for all hosts
  ansible.builtin.include_tasks: common.yml
  when: all_base_settings

- name: Users and groups
  ansible.builtin.include_tasks: users.yml
  when: main_users_and_groups

- name: Update cache tools and purge
  ansible.builtin.include_tasks: packages.yml
  when: simple_tools_update_cache 